### ISSUE TITLE
When generating `Privacy Manifest Report` getting the following error [ iOS ]

### ISSUE THREAD

**Issue by n3rdkid** [windows7lake/app_badge_plus#4]
Was trying to create `Privacy manifest` for my application and while doing so got the following error for this plugin.

<img width="581" alt="Screenshot 2024-07-19 at 11 53 30" src="https://github.com/user-attachments/assets/d69ea7bc-54ad-44f4-9a6f-a8231fbc4684">

There does seem to be the `Privacy Manifest` file [here](https://github.com/windows7lake/app_badge_plus/blob/main/ios/PrivacyInfo.xcprivacy).
Not sure if this is an issue. Please let me know if I am missing something.

**Comment by windows7lake** [comment]
@n3rdkid Sorry for that, I had been updated `Privacy Manifest` and release on 1.1.1. Please upgrade to new version, and tell me something if it doesn't work. Thnaks!

**Comment by n3rdkid** [comment]
@windows7lake Thank you for your quick response. 🎉
