### ISSUE TITLE
Document limitations vs. `flutter_app_badger`

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [windows7lake/app_badge_plus#5]
I am really excited to see this new plugin released since the previously most popular plugin [`flutter_app_badger`](https://pub.dev/packages/flutter_app_badger) has [recently been discontinued](https://github.com/g123k/flutter_app_badger/commit/7a36a769b1d1eb42728dd5cc44c60a87e616dee5).

Since `app_badge_plus` is so fresh, I was wondering if you could add a section to the README that details limitations when compared to `flutter_app_badger`, assuming you have not yet been able to implement all functionality.

Thanks a lot for your work!

**Comment by windows7lake** [comment]
Thanks for your advice. Fixed now.
