### ISSUE TITLE
Make requesting notification permissions optional/explicit

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [windows7lake/app_badge_plus#6]
In the current implementation, [`enableNotification` is always called](https://github.com/windows7lake/app_badge_plus/blob/bd668659f5010ef6dffe6cf2562258d640cfb66e/ios/Classes/AppBadgePlusPlugin.swift#L20) when using the plugin.

It would be very beneficial if it was possible to be explicit about requesting notification permissions instead and make requesting the notification permission optional instead.  
The use case for this is having custom logic for requesting notification permissions in general.

**Comment by windows7lake** [comment]
Removed `enableNotification` in iOS. And you can use permission_handler to manager permission by youself.
