### ISSUE TITLE
SecurityException | Missing permission to insert badges

### ISSUE THREAD

**Issue by pranavo72bex** [windows7lake/app_badge_plus#8]
I am getting this sentry exception.
Device : SONY Xperia 
OS: Android 9

**Comment by windows7lake** [comment]
<uses-permission android:name="com.sec.android.provider.badge.permission.READ"/>
<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE"/>


<uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS"/>
<uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT"/>


<uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE"/>
<uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE"/>


<uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT"/>


<uses-permission android:name="com.majeur.launcher.permission.UPDATE_BADGE"/>


<uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE" />
<uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS" />
<uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS" />

**Comment by windows7lake** [comment]
@pranavo72bex add permission above, I will fixed doc. Sorry.

**Comment by pranavo72bex** [comment]
> ```
> 
> 
> <uses-permission android:name="com.sec.android.provider.badge.permission.READ"/>
> <uses-permission android:name="com.sec.android.provider.badge.permission.WRITE"/>
> 
> 
> <uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS"/>
> <uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT"/>
> 
> 
> <uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE"/>
> <uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE"/>
> 
> 
> <uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT"/>
> 
> 
> <uses-permission android:name="com.majeur.launcher.permission.UPDATE_BADGE"/>
> 
> 
> <uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE" />
> <uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS" />
> <uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS" />
> 
> ```

We have to give these permission? It is not mention in ReadME or in Example 🤔 . It will be helpful if you can provide the reference 🙏
